<?php

return array(

	/*
	|--------------------------------------------------------------------------
	| Data for contact
	|--------------------------------------------------------------------------
	|
	| Here you may specify additional classes to include in the compiled file
	| generated by the `artisan optimize` command. These should be classes
	| that are included on basically every request into the application.
	|
	*/

	'phoneRegular'				=> '06 60 64 71 60',
	'phoneInternationale'		=> '+33660647160'


);